### ISSUE TITLE
有的字好像没有

### ISSUE THREAD

**Issue by shinshinran** [howl-anderson/hanzi_chaizi#1]
报这个错误应该是没有找到字吧
print(hc.query('嶶'))
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    print(hc.query('嶶'))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\hanzi_chaizi-0.1-py3.7.egg\hanzi_chaizi\__init__.py", line 15, in query
    return result[0]
TypeError: 'NoneType' object is not subscriptable

**Comment by howl-anderson** [comment]
感谢反馈！由于本人最近较忙，我会尽快处理这个issue, 找出 root cause。

**Comment by shinshinran** [comment]
一,民,长,又,沉,之,卐,骨,耳,马,凹,凸,毋,丨,長,氏,馬,乙,舎, 这几个字也拆不了，报这个错误TypeError: 'NoneType' object is not subscriptable

**Comment by howl-anderson** [comment]
@LangXiu 非常感谢你的反馈！我会尽快处理这些问题。

**Comment by pgshow** [comment]
3年了，长还是不能解析、

**Comment by wangzhione** [comment]
`
2025-11-28 16:10:54,409 - ERROR - pianpangbushoutSimilar 错误: charOne='尾', charTwo='角', 错误信息: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "hanzi_sim.py", line 166, in pianpangbushoutSimilar
    result_two = hc.query(charTwo)
  File "miniforge/envs/paddleppv5/lib/python3.10/site-packages/hanzi_chaizi/hanzi_chaizi.py", line 15, in query
    return result[0]
TypeError: 'NoneType' object is not subscriptable

2025-11-28 16:10:54,521 - ERROR - pianpangbushoutSimilar 错误: charOne='齿', charTwo='角', 错误信息: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/logs/zhi.wang/extract_noun/cha_utils/hanzi_sim.py", line 166, in pianpangbushoutSimilar
    result_two = hc.query(charTwo)
  File "miniforge/envs/paddleppv5/lib/python3.10/site-packages/hanzi_chaizi/hanzi_chaizi.py", line 15, in query
    return result[0]
TypeError: 'NoneType' object is not subscriptable
`

你好是不是也是一样的原因. 要不解决下, 发个 0.3 😂

**Comment by wangzhione** [comment]
```
# 使用 hanzi_chaizi 查询字符拆分结果
# 由于库存在 bug，当字符不存在时会抛出 TypeError，需要捕获异常
try:
    result_one = hc.query(charOne)
    # 检查查询结果是否为 None
    if result_one is None:
        logger.debug(f"pianpangbushoutSimilar: hc.query('{charOne}') 返回 None，使用字符本身")
        result_one = [charOne]
except (TypeError, AttributeError, IndexError) as e:
    # 库内部访问 None[0] 时会抛出 TypeError，此时返回字符本身
    logger.debug(f"pianpangbushoutSimilar: hc.query('{charOne}') 抛出异常 {type(e).__name__}，使用字符本身")
    result_one = [charOne]
```


我用这样方式暂时规避里面返回的细节了.

**Comment by howl-anderson** [comment]
Hi @LangXiu @pgshow @wangzhione 以及所有曾经路过这个 issue 的朋友们，

首先真的要感谢大家一路以来的反馈、补充、追问和“提醒我这个项目还活着”。
不得不承认，这个 issue 的存在时间已经有点像《无间道》里那句名台词——

 >  “三年又三年，我都快忘了我是谁了……”

过去这些年我这边确实事情比较多，一些 issue（包括这个）真的被淹没在历史长河里了。
但大家陆续追加的留言我都有看到，也很感谢你们提供的测试用例、异常日志，以及 @wangzhione 的临时 workaround。

我会重新把这个问题捞上来，修一波；
如果今年的事情实在太多，那我会确保在 2026 年之前一定彻底解决，不会再继续“三年又三年”下去

再次感谢各位的耐心和贡献！如果你们还有更多不能拆的字、边角 case 或修复建议，都欢迎继续留言，我会一并处理。

**Comment by howl-anderson** [comment]
各位大佬们，小弟幸不辱命，在2026年年前按照承诺，对该bug进行了修复，也对代码进行了加强，完成了对构建系统的现代化和CI系统的强化。

真诚感激各位大佬不离不弃，小弟后续会继续努力的！

(PS：关于不能拆解的字，我建立了一个列表收集。因为自己不是文字方面的专家，所以暂时不能修复，但我会尽力找资源完善的！
