### ISSUE TITLE
python3.7 不支持

### ISSUE THREAD

**Issue by ketra21** [howl-anderson/hanzi_chaizi#4]
python3.7 不支持，3.6可以

**Comment by howl-anderson** [comment]
什么样的错误信息呢？

**Comment by ketra21** [comment]
(base) [root@root hanzi_chaizi-master]# python setup.py install
running install
running bdist_egg
running egg_info
writing hanzi_chaizi.egg-info/PKG-INFO
writing dependency_links to hanzi_chaizi.egg-info/dependency_links.txt
writing top-level names to hanzi_chaizi.egg-info/top_level.txt
reading manifest file 'hanzi_chaizi.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'hanzi_chaizi.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/hanzi_chaizi
copying build/lib/hanzi_chaizi/__init__.py -> build/bdist.linux-x86_64/egg/hanzi_chaizi
creating build/bdist.linux-x86_64/egg/hanzi_chaizi/data
copying build/lib/hanzi_chaizi/data/data.pkl -> build/bdist.linux-x86_64/egg/hanzi_chaizi/data
byte-compiling build/bdist.linux-x86_64/egg/hanzi_chaizi/__init__.py to __init__.cpython-37.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying hanzi_chaizi.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hanzi_chaizi.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hanzi_chaizi.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying hanzi_chaizi.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    include_package_data=True
  File "/root/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/root/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/root/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/python3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/python3.6/lib/python3.6/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/root/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/python3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/local/python3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/local/python3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/local/python3.6/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

**Comment by howl-anderson** [comment]
收到详细信息，后续查找问题并修复，感谢支持！

**Comment by JohnMingbo** [comment]
请问楼主修复了吗

**Comment by qcgm1978** [comment]
python3.10 works
